import { StyleSheet } from 'react-native';
import { hp, wp, rf } from '../../components/Responvie';
import Colors, { Fonts } from '../../utils/Colors';
import { RFPercentage } from 'react-native-responsive-fontsize';

export const Styles = StyleSheet.create({
  Splash_Container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashLogo: {
    // width: hp(100),
    // height: hp(100),
    // flex: 1,
    width: wp(100),
    height: hp(10),
    // resizeMode: 'contain',
  },
  main_container: {
    backgroundColor: Colors.background,
    flex: 1,
    paddingHorizontal: 12,
  },
  DropDownCoatinier: {
    // marginTop: 10,
    top: hp(2),
    right: 12,
    alignSelf: 'flex-end',
    position: 'absolute',
    zIndex: 1,
  },
  dropdwonbutton: {
    borderWidth: 1,
    borderColor: Colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderRadius: 5,
    justifyContent: 'center',
  },
  dropDownImage: {
    width: wp(3),
    height: wp(3),
    resizeMode: 'contain',
    marginLeft: 10,
  },
  dropDownMenu: {
    borderWidth: 1,
    borderColor: Colors.white,
    backgroundColor: Colors.background,
    marginTop: 5,
    borderRadius: 5,
    alignSelf: 'flex-end',
  },
  selectLanguageText: {
    color: Colors.white,
    fontSize: rf(15),
    fontFamily: Fonts.pop500,
    padding: 8,
    textAlign: 'center',
  },
  HindiEnlgtext: {
    textAlign: 'center',
    fontSize: rf(15),
    fontFamily: Fonts.Pop400,
    color: Colors.white,
  },
  Welcometext: {
    color: Colors.primary,
    fontSize: rf(30),
    fontFamily: Fonts.pop500,
  },
  centerConatiner: { flex: 1, justifyContent: 'center' },
  Acdoctortext: {
    color: Colors.white,
    fontSize: rf(46),
    fontFamily: Fonts.pop700,
    padding: 0,
  },
  TextLabel: {
    color: Colors.white,
    fontSize: rf(18),
    fontFamily: Fonts.pop500,
  },
  rowConatiner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.lightGray,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 5,
  },
  smallicon: { width: wp(5), height: wp(5) },
  loginSubtitle: {
    color: Colors.white,
    fontSize: rf(12),
    width: wp(85),
    fontFamily: Fonts.pop300,
  },
  logntitle: {
    color: Colors.primary,
    fontSize: rf(30),
    fontFamily: Fonts.pop500,
    width: wp(72),
    marginTop: hp(-10),
  },
  phonecontainer: {
    backgroundColor: Colors.background,
    marginBottom: 40,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 18,
  },
  countryCodeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.lightGray,
    height: hp(5.9),
    borderRadius: 5,
    paddingHorizontal: 14,
  },
  flag: { width: wp(6), height: wp(6), marginRight: 8 },
  CountrcodeText: {
    fontSize: rf(14),
    fontFamily: Fonts.pop500,
    color: Colors.white,
  },
  phoneInput: {
    backgroundColor: Colors.lightGray,
    flex: 1,
    height: hp(5.9),
    fontSize: RFPercentage(2),
    color: Colors.white,
    marginLeft: 8,
    borderRadius: 5,
    fontFamily: Fonts.pop500,
    paddingHorizontal: 5,
  },
  gretingtext: {
    color: Colors.white,
    fontSize: rf(16),
    fontFamily: Fonts.pop500,
    marginTop: 30,
  },
  pleasefillthebelow: {
    color: Colors.white,
    fontSize: rf(12),
    fontFamily: Fonts.pop300,
    marginTop: 5,
  },
  InputLable: {
    color: Colors.white,
    fontSize: rf(14),
    fontFamily: Fonts.pop600,
    marginTop: 18,
  },
  GednerContainer: {
    borderWidth: 1,
    borderColor: Colors.white,
    borderRadius: 13,
    height: hp(5),
    width: wp(29),
    justifyContent: 'center',
    alignItems: 'center',
  },
  HardCoenumberconater: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    height: hp(5),
    paddingHorizontal: 14,
    borderRadius: 13,
    marginRight: 10,
    borderColor: Colors.white,
  },
  alternatenumber: {
    borderWidth: 1,
    // borderColor: Colors.white,
    borderRadius: 13,
    height: hp(5),
    paddingHorizontal: 14,
    flex: 1,
    justifyContent: 'center',
    color: Colors.white,
    fontSize: rf(14),
    fontFamily: Fonts.pop600,
  },
  cehckuncheck: { width: wp(3.5), height: wp(3.5) },
  AddharcardText: {
    fontSize: rf(14),
    fontFamily: Fonts.pop600,
    color: Colors.gray,
    marginTop: 9,
  },
  aadhrupaloadImagestyle: {
    width: wp(7),
    height: wp(7),
    resizeMode: 'contain',
  },
  aadhraclicablestyle: {
    backgroundColor: Colors.lightGray,
    alignItems: 'center',
    justifyContent: 'center',
    height: hp(18),
    marginTop: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: Colors.gray,
  },
  contacustext: {
    color: Colors?.primary,
    fontSize: rf(15),
    fontFamily: Fonts?.pop700,
  },
});
